### ISSUE TITLE
Is anyway to dec already downloaded .ts samples?

### ISSUE THREAD

**Issue by dEROZA** [pensnarik/boomstream-downloader#1]
Need to decode .ts parts on local. Thx for help.
I need get a courses, free access for them to 20 July, and I can't view all them :\

I've got in chunklist
`#EXT-X-KEY:METHOD=AES-128,URI="[KEY]",IV=[IV]`
and I not fully understand how I can get KEY and IV

> I've access to the video and can view it

openssl supports a lot of chippers, which used for?
`-aes-128-cbc               -aes-128-ccm               -aes-128-cfb
-aes-128-cfb1              -aes-128-cfb8              -aes-128-ctr
-aes-128-ecb               -aes-128-ofb`

For example

> ```#EXT-X-MEDIA-READY:57091518060b563b2f03161420323a0b1c140837180d5b3509251b3e023a2f2b0711150e```
> ```#EXTINF:6.0, https://cdn-skb-m9.boomstream.com/vod/hash:6098c2fdd72683e9f1ba5380e077e70c/id:12985.14487.420095.25670143.75377.hls/time:0/data:eyJ0aXRsZSI6IjAiLCJ1c2VfZGlyZWN0X2xpbmtzIjoieWVzIiwiaXNfZW5jcnlwdCI6InllcyJ9/m49/2019/10/11/UUAk8mIj.mp4/media-16.ts```

**Comment by pensnarik** [comment]
Boomstream uses `aes-128-cbc` encryption method. I described in project README how KEY and IV values are stored and extracted. But I'm not sure you can get them if you don't have your session token saved which is stored in boomstream config JSON array.

**Comment by pensnarik** [comment]
If you still have access to the videos why don't you use `boomstream-downloader.py` script to download them?

**Comment by dEROZA** [comment]
> Boomstream uses `aes-128-cbc` encryption method. I described in project README how KEY and IV values are stored and extracted. But I'm not sure you can get them if you don't have your session token saved which is stored in boomstream config JSON array.

As I understand after some updates there're no more "config JSON"

**Comment by dEROZA** [comment]
> If you still have access to the videos why don't you use `boomstream-downloader.py` script to download them?

Can't find "config", not works :'|

**Comment by pensnarik** [comment]
`boomstream.config.json` is a temporary file created by `boomstream-downloader.py` script which contents boomstream config JSON array parsed from video HTML page.
